name: CI

on: 
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install requirements
      run: npm install
    - name: Run a one-line script
      run: npm run screener-storybook
